name: wedolawns
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6
  intl: ^0.20.1

  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  build_runner: ^2.4.14
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
