name: wedolawns
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6
  intl: ^0.20.1

  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  build_runner: ^2.4.14
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  flutter_phoenix: ^1.1.1
  loader_overlay: ^5.0.0
  flutter_svg: ^2.0.17
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.2
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/svgs/
    - fonts/

  fonts:
    - family: "WeDoLawns"
      fonts:
        - asset: fonts/Bellefair-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"
